// <auto-generated />
using System;
using CSVC_PTIT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSVC_PTIT.Data.Migrations
{
    [DbContext(typeof(CsvcDbContext))]
    [Migration("20260628022750_AddBusinessRules")]
    partial class AddBusinessRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("asset_code");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("asset_name");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("availability_status");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int")
                        .HasColumnName("available_quantity");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("brand");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("ConditionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("condition_status");

                    b.Property<int?>("CurrentRoomId")
                        .HasColumnType("int")
                        .HasColumnName("current_room_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ManagementMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("management_mode");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("serial_number");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int")
                        .HasColumnName("total_quantity");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("AssetId");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrentRoomId");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.AssetCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("asset_categories", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("ActualReturnAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_return_at");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BorrowEndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("borrow_end_at");

                    b.Property<DateTime>("BorrowStartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("borrow_start_at");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpectedReturnAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expected_return_at");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("priority_level");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reject_reason");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("request_code");

                    b.Property<string>("RequestNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("request_note");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("request_type");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("RequestId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.ToTable("borrow_requests", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequestAsset", b =>
                {
                    b.Property<int>("RequestAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestAssetId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("ItemNote")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("item_note");

                    b.Property<int>("QuantityApproved")
                        .HasColumnType("int")
                        .HasColumnName("quantity_approved");

                    b.Property<int>("QuantityCheckedOut")
                        .HasColumnType("int")
                        .HasColumnName("quantity_checked_out");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int")
                        .HasColumnName("quantity_requested");

                    b.Property<int>("QuantityReturned")
                        .HasColumnType("int")
                        .HasColumnName("quantity_returned");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("RequestAssetId");

                    b.HasIndex("AssetId");

                    b.HasIndex("RequestId", "AssetId")
                        .IsUnique();

                    b.ToTable("borrow_request_assets", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequestRoom", b =>
                {
                    b.Property<int>("RequestRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestRoomId"));

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("UsageNote")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("usage_note");

                    b.HasKey("RequestRoomId");

                    b.HasIndex("RoomId");

                    b.HasIndex("RequestId", "RoomId")
                        .IsUnique();

                    b.ToTable("borrow_request_rooms", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Checkout", b =>
                {
                    b.Property<int>("CheckoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("checkout_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutId"));

                    b.Property<int>("CheckedOutBy")
                        .HasColumnType("int")
                        .HasColumnName("checked_out_by");

                    b.Property<int>("CheckedOutTo")
                        .HasColumnType("int")
                        .HasColumnName("checked_out_to");

                    b.Property<DateTime>("CheckoutAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checkout_at");

                    b.Property<string>("CheckoutCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("checkout_code");

                    b.Property<string>("CheckoutNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("checkout_note");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("CheckoutId");

                    b.HasIndex("CheckedOutBy");

                    b.HasIndex("CheckedOutTo");

                    b.HasIndex("CheckoutCode")
                        .IsUnique();

                    b.HasIndex("RequestId");

                    b.ToTable("checkouts", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.CheckoutItem", b =>
                {
                    b.Property<int>("CheckoutItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("checkout_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutItemId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int>("CheckoutId")
                        .HasColumnType("int")
                        .HasColumnName("checkout_id");

                    b.Property<string>("ConditionBefore")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("condition_before");

                    b.Property<bool>("IsReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_returned");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("RequestAssetId")
                        .HasColumnType("int")
                        .HasColumnName("request_asset_id");

                    b.HasKey("CheckoutItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("RequestAssetId");

                    b.ToTable("checkout_items", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.DamageReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<decimal>("ActualCompensation")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_compensation");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("EstimatedCompensation")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_compensation");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("incident_type");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reported_at");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int")
                        .HasColumnName("reported_by");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_user_id");

                    b.Property<int?>("ReturnItemId")
                        .HasColumnType("int")
                        .HasColumnName("return_item_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("ReportId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("RequestId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("ReturnItemId");

                    b.HasIndex("Status");

                    b.ToTable("damage_reports", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("department_code");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("department_name");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Return", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("return_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int>("CheckoutId")
                        .HasColumnType("int")
                        .HasColumnName("checkout_id");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedBy")
                        .HasColumnType("int")
                        .HasColumnName("received_by");

                    b.Property<string>("ReturnNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("return_note");

                    b.Property<DateTime>("ReturnedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("returned_at");

                    b.Property<int>("ReturnedBy")
                        .HasColumnType("int")
                        .HasColumnName("returned_by");

                    b.HasKey("ReturnId");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("ReturnedBy");

                    b.ToTable("returns", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.ReturnItem", b =>
                {
                    b.Property<int>("ReturnItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("return_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnItemId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int>("CheckoutItemId")
                        .HasColumnType("int")
                        .HasColumnName("checkout_item_id");

                    b.Property<string>("ConditionAfter")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("condition_after");

                    b.Property<string>("DamageNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("damage_note");

                    b.Property<bool>("IsDamaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_damaged");

                    b.Property<bool>("IsLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_lost");

                    b.Property<int>("QuantityReturned")
                        .HasColumnType("int")
                        .HasColumnName("quantity_returned");

                    b.Property<int>("ReturnId")
                        .HasColumnType("int")
                        .HasColumnName("return_id");

                    b.HasKey("ReturnItemId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CheckoutItemId");

                    b.HasIndex("ReturnId");

                    b.ToTable("return_items", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Building")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("building");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int?>("FloorNo")
                        .HasColumnType("int")
                        .HasColumnName("floor_no");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("room_code");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("room_name");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("room_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.SystemConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("SystemConfigs", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("BorrowerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("borrower_type");

                    b.Property<string>("ClassName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdentityNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("identity_no");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("student_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .HasFilter("[employee_code] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("StudentCode")
                        .HasFilter("[student_code] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Asset", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.AssetCategory", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.Room", "CurrentRoom")
                        .WithMany("Assets")
                        .HasForeignKey("CurrentRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("CurrentRoom");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequest", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.User", "Approver")
                        .WithMany("ApprovedRequests")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CSVC_PTIT.Data.Entities.User", "Requester")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequestAsset", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.Asset", "Asset")
                        .WithMany("BorrowRequestAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.BorrowRequest", "BorrowRequest")
                        .WithMany("BorrowRequestAssets")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("BorrowRequest");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequestRoom", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.BorrowRequest", "BorrowRequest")
                        .WithMany("BorrowRequestRooms")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.Room", "Room")
                        .WithMany("BorrowRequestRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BorrowRequest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Checkout", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.User", "CheckedOutByUser")
                        .WithMany()
                        .HasForeignKey("CheckedOutBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.User", "CheckedOutToUser")
                        .WithMany()
                        .HasForeignKey("CheckedOutTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.BorrowRequest", "BorrowRequest")
                        .WithMany("Checkouts")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BorrowRequest");

                    b.Navigation("CheckedOutByUser");

                    b.Navigation("CheckedOutToUser");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.CheckoutItem", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.Asset", "Asset")
                        .WithMany("CheckoutItems")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.Checkout", "Checkout")
                        .WithMany("CheckoutItems")
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.BorrowRequestAsset", "BorrowRequestAsset")
                        .WithMany("CheckoutItems")
                        .HasForeignKey("RequestAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("BorrowRequestAsset");

                    b.Navigation("Checkout");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.DamageReport", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.Asset", "Asset")
                        .WithMany("DamageReports")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.BorrowRequest", "BorrowRequest")
                        .WithMany("DamageReports")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.ReturnItem", "ReturnItem")
                        .WithMany("DamageReports")
                        .HasForeignKey("ReturnItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("BorrowRequest");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("ReturnItem");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Notification", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Return", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.Checkout", "Checkout")
                        .WithMany("Returns")
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.User", "ReturnedByUser")
                        .WithMany()
                        .HasForeignKey("ReturnedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("ReturnedByUser");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.ReturnItem", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.Asset", "Asset")
                        .WithMany("ReturnItems")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.CheckoutItem", "CheckoutItem")
                        .WithMany("ReturnItems")
                        .HasForeignKey("CheckoutItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSVC_PTIT.Data.Entities.Return", "Return")
                        .WithMany("ReturnItems")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("CheckoutItem");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.User", b =>
                {
                    b.HasOne("CSVC_PTIT.Data.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CSVC_PTIT.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Asset", b =>
                {
                    b.Navigation("BorrowRequestAssets");

                    b.Navigation("CheckoutItems");

                    b.Navigation("DamageReports");

                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.AssetCategory", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequest", b =>
                {
                    b.Navigation("BorrowRequestAssets");

                    b.Navigation("BorrowRequestRooms");

                    b.Navigation("Checkouts");

                    b.Navigation("DamageReports");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.BorrowRequestAsset", b =>
                {
                    b.Navigation("CheckoutItems");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Checkout", b =>
                {
                    b.Navigation("CheckoutItems");

                    b.Navigation("Returns");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.CheckoutItem", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Return", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.ReturnItem", b =>
                {
                    b.Navigation("DamageReports");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.Room", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("BorrowRequestRooms");
                });

            modelBuilder.Entity("CSVC_PTIT.Data.Entities.User", b =>
                {
                    b.Navigation("ApprovedRequests");

                    b.Navigation("BorrowRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
